### ISSUE TITLE
TED Talks are downloaded multiple times

### ISSUE THREAD

**Issue by thomasboehm** [managementboy/mntv#16]
Hi, i just noticed that all my TED Talks are getting downloaded at least two times. I'm using this URL http://feeds.feedburner.com/TedtalksHD?format=xml

I checked the actual xml and the podcast are not listed twice, but the url appears twice, once within the <media:content> tag and once within the <enclosure> tag. Is this a problem with mythnettv or the xml?

Edit: It appears that it only happens with podcasts published before 2015-02-09. So I think TED changeD something on that date. Can anyone confirm this?

**Comment by managementboy** [comment]
Hi Thomas, this is a problem of the TEDTalk feed. They post a video with a spelling mistake, then fix it a few hours later. Mythnettv assumes these are two different shows and downloads them again. No fix possible.
