### ISSUE TITLE
Episode Numbers with more than 2 digits

### ISSUE THREAD

**Issue by thomasboehm** [managementboy/mntv#17]
Hi, I'm not 100% sure whether it is a mythnettv problem, but usually mythtv recognizes episode numbers with more than 2 digits. When I import a show with S08E114 in the subtitle like

mythnettv --importlocal "This Show S08E114 This Episode.mkv" "This Show" "This Show S08E114 This Episode"

it writes 11 in the episode column in the recorded table and the metadata lookup returns the data for episode 11.

**Comment by managementboy** [comment]
this is a bug. The current code does not look for Seasons or Episodes with 3 or more digits.
