### ISSUE TITLE
How to get Youtube working again

### ISSUE THREAD

**Issue by thomasboehm** [managementboy/mntv#18]
Hi,

I'm trying to get mythnettv to work again with Youtube. I found out here
https://www.youtube.com/watch?v=bszheiv5tRo
how to obtain the url of the RSS feed. It has the format
https://www.youtube.com/feeds/videos.xml?channel_id=CHANNEL_ID

When I change my mythnettv subscriptions accordingly, I get the following errors

```
Downloading 06a40c3bec0edb4a21bb6e9f77cce897
Destination directory will be /tmp
Downloading Youtube: Shooting Self in face... high speed science experiment!

YouTubeID:   http://www.youtube.com/watch?v=okyzcngHxhI
Downloading "http://www.youtube.com/watch?v=okyzcngHxhI"...

Download Error: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/share/mythnettv/mythnettvcore.py", line 122, in DownloadAndImport
    out=out) == True:
  File "/usr/local/share/mythnettv/program.py", line 544, in Download
    total = streamingsites.Download('YouTube', youtubeid, datadir)
  File "/usr/local/share/mythnettv/plugins/streamingsites.py", line 27, in Download
    download = subprocess.Popen(['/usr/bin/youtube-dl', '--restrict-filenames', identifier], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I have youtube-dl version 2015.10.16 installed.

What else needs to be done?

**Comment by managementboy** [comment]
new versions of youtube-dl merge files to an MKV. As the original download file gets deleted, it can't be found by myhtnettv. Using the "--verbose" output from mythnettv you will see something like: [ffmpeg] Merging formats into. I tried to create a way of parsing this... not well tested but uploaded to git anyway. Test and feedback.

**Comment by thomasboehm** [comment]
Thanks for working on it. Now I'm getting
```
~$ /usr/src/mntv/mythnettv update
Traceback (most recent call last):
  File "/usr/src/mntv/mythnettv", line 831, in <module>
    main(sys.argv)
  File "/usr/src/mntv/mythnettv", line 525, in main
    mythnettvcore.Update(out, title)
  File "/usr/src/mntv/mythnettvcore.py", line 173, in Update
    syndication.Sync(db, xmlfile, row['title'], out=out)
  File "/usr/src/mntv/syndication.py", line 248, in Sync
    if not done and entry['link'].startswith('http://www.youtube') or entry['link'].startswith('https://www.youtube'):
  File "/usr/lib/python2.7/dist-packages/feedparser.py", line 383, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'link'
```

**Comment by managementboy** [comment]
Can you post the user or channel URL you are using?
Am 30.10.2015 13:43 schrieb "thomasboehm" <notifications@github.com>:

**Comment by thomasboehm** [comment]
I use these two URLs

https://www.youtube.com/feeds/videos.xml?channel_id=UCH_zYYXkJpULueOVZTkY4Bw
https://www.youtube.com/feeds/videos.xml?channel_id=UCmb8hO2ilV9vRa8cilis88A
